name: task_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  build_runner: ^2.4.13
  cloud_firestore: ^5.5.0
  custom_lint: ^0.7.0
  equatable: ^2.0.7
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.2
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
